### ISSUE TITLE
Help getting custom renderer working

### ISSUE THREAD

**Issue by DSchau** [peerigon/markdown-loader#10]
I'm trying to get a custom renderer working with the markdown loader, and I haven't had any luck. It doesn't look like anything I'm doing is wrong, but then when I look at the code for the loader, it all looks good, as well. 

So... if you have any time, I was hoping you could take a quick look at my current set up and see if anything looks wrong at a glance. If it doesn't, I'll keep looking and will try to figure out exactly what's going on.

Some things to note:

1. The custom highlight and turning sanitize off work as I'd expect
2. Calling renderer.code('sample') prior to it being on the options object passed to Marked (via markdown-loader) works fine and outputs the code. However, when it's merged with the other options, it doesn't seem to work.

At a glance, anything look incorrect?

#### webpack.config.js

```javascript
module.exports = {
  module: {
    loaders: [
      {
        test: /\.md$/,
        loaders: ['html', 'markdown']
      }
    ]
  },
  markdownLoader: require('./build/webpack/markdown-options')
};
```

#### build/webpack/markdown-options.js

```javascript
module.exports = {
  renderer: require('./markdown-renderer'),
  highlight: function(code) {
    return require('highlight.js').highlightAuto(code).value;
  },
  sanitize: false
};
```

#### build/webpack/markdown-renderer.js

Note that this isn't actually what I'm trying to do, but just to illustrate that the custom code renderer isn't being called.

```javascript
/* globals escape */
var marked = require('marked');
var renderer = new marked.Renderer();

renderer.code = function(code, lang, escaped) {
  console.log(code);
  return code;
};

module.exports = renderer;
```

**Comment by meaku** [comment]
@DSchau i tried to reproduce your problem but everything worked as expected. Your example looks perfectly fine. Did you already solve the problem or can you give me more details?

**Comment by DSchau** [comment]
Enjoying the holiday currently, but I'll try to get you more details on Monday! Thank you so much for replying back.

**Comment by meaku** [comment]
No worries and sorry for the delay! Enjoy your holiday.

**Comment by DSchau** [comment]
@meaku Been super busy lately, so I'll just close this for now!

I'll let you know when/if I can get you a test case or something.

**Comment by DSchau** [comment]
Just a heads up that it was related to the usage of [`clone`](https://github.com/pvorb/node-clone).

Seems like it *should* be doing a deep copy of all objects and properties, but it ended up removing the methods from the `markdownLoader` configuration property.

Thanks for the sanity check!
