### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by qiuyuntao** [peerigon/markdown-loader#11]
I use this loader to load `*.md`

```
var html = require("html!markdown!./README.md");
console.log(html)
```

`html` is `<p>module.exports = &quot;<h3 id=\"example\">Example</h3>\n<ul>\n<li><code>npm install</code></li>\n<li><code>webpack-dev-server</code></li>\n</ul>\n&quot;;</p>`

it is a string, I just want to use like this `var container = document.getElementById('container');
 container.innerHTML = html;`

Why comes `module.exports = &quot;`, then how can I use?

**Comment by qiuyuntao** [comment]
I have found what problem is. In `webpack.config.js` I have writed
```
module: {
    loaders: [{
      test: /\.md$/,
      loader: "html!markdown?gfm=false"
    }]
  },
```

So, I require `var html = require("./README.md");` rather than `require("html!markdown!./README.md")`.

Please close this issue

**Comment by meaku** [comment]
No worries!

**Comment by qiuyuntao** [comment]
I wirte `markdown` like this 

![Alt text](https://os.alipayobjects.com/rmsportal/dAwgWgMwnVUWtTh.png)
Normally, it render a mutiply lines, but indeed it render as a single line code.
![Alt text](https://os.alipayobjects.com/rmsportal/aJwQumtVCgPuaCF.png)
Is it a bug about `markdown-loader`?

**Comment by meaku** [comment]
The loader uses [marked](https://www.npmjs.com/package/marked) as a renderer and simply returns the response. So rendering issues are part of marked and you should check if there is some configuration option there. You could also pass your own marked or markdown renderer if you like via options

**Comment by qiuyuntao** [comment]
@meaku Thanks, I got it

**Comment by luandro** [comment]
> So, I require var html = require("./README.md"); rather than require("html!markdown!./README.md").

This should be noted on the README. It took me a while to figure out why `module.exports = ` was being ouputed.

**Comment by qiuyuntao** [comment]
@luandro you can see `folder demo` in this project. I think code is the best doc.

**Comment by iheartrachie** [comment]
@qiuyuntao thanks for posting your solution. I came across the same thing and was a bit confused.

**Comment by qiuyuntao** [comment]
@iheartrachie what makes you confuse?
