### ISSUE TITLE
Images inside markdown

### ISSUE THREAD

**Issue by kevinsimper** [peerigon/markdown-loader#13]
I am trying to load images inside the article, but it does not seem to work.

It generates a file that is called

```
<img src="xxxHTMLLINKxxx0.5461799555923790.5964239498134702xxx" alt="header.jpg">
```

which obivious does not exist.

**Comment by kevinsimper** [comment]
I made a mistake in my webpack.config.js

**Comment by mran3** [comment]
I was having the same problem, my mistake was that I have two configs for html-loader inside webpack.config.js, leaving just this one, solved the problem for me:

`{
                test: /\.html$/,
                loader: 'html-loader',
                options: {
                    minimize: true,
                    interpolate: true
                }
            }`
