### ISSUE TITLE
Add support for syntax highlighting

### ISSUE THREAD

**Issue by bebraw** [peerigon/markdown-loader#2]
If you are interested, I think you can add syntax highlighting to the library quite easily. Here's the basic idea:

```javascript
var highlight = require('highlight.js');

marked.setOptions({
    highlight: function(code) {
        return highlight.highlightAuto(code).value;
    }
});
```

This is the synchronous way to deal with it. There is also an async way to do this if needed.

**Comment by meaku** [comment]
Yeah! Sounds like a good idea. I think using the sync version should be fine during the bundling process. The async version (https://github.com/rvagg/node-pygmentize-bundled) has python dependencies and seems more error prone than using the js-only highlightjs.

**Comment by bebraw** [comment]
Yeah, it probably doesn't make much of a difference. `highlight.js` has worked fine for my purposes.

**Comment by jhnns** [comment]
Just out of curiosity: Does this need to be applied *while* compiling? It would be nicer, to have a separate highlight-loader, which is placed *after* the markdown-loader. Then the highlight-loader could been used with any arbitrary html.

**Comment by bebraw** [comment]
@jhnns That's a much better idea! If it's possible to do it that way, sure. :)

**Comment by meaku** [comment]
@jhnns how would you do it? The highlight function we wanted to use is part of _marked_. Using a separate loader we need a way to find the code parts in markdown manually.

**Comment by bebraw** [comment]
@meaku What if it should go other way around? The filter would first replace Markdown code parts using highlight.js (you can hook into marked lexer to detect). After that you would perform the current transformation. I think it should skip html when performing the conversion.

So instead of doing filter `markdown -> highlight` you would do `highlight -> markdown`. That might sound a bit backwards but I don't see why it could work as long as you can build pipes like this within Webpack declaration.

**Comment by jhnns** [comment]
@bebraw Yep, but it's probably even more useful the other way round. Markdown generates `<code>`-blocks afaik which can then be parsed to be highlighted. This way *any* HTML regardless of the source could be highlighted.

**Comment by bebraw** [comment]
@jhnns Well that's true. Maybe a simple `replace` would be enough then. :)

**Comment by bebraw** [comment]
Any progress with this? The core logic should be pushed to a `highlight-loader`? Then you would just pipe to that. Poke me at Webpack gitter if you want to collaborate on this. It would be nice to get that done. :)

**Comment by meaku** [comment]
Sorry, but we are very busy at the moment and the markdown loader has no prio atm. Maybe you can make a PR?

**Comment by bebraw** [comment]
@meaku No probs. I'll try to whip up something. :)

**Comment by meaku** [comment]
That would be great! Thanks man

**Comment by bebraw** [comment]
@meaku First pass done, https://www.npmjs.com/package/highlight-loader . Closing this issue given it's sort of redundant now.
