### ISSUE TITLE
Not possible to escape the '|' (pipe) sign.

### ISSUE THREAD

**Issue by Lazarencjusz** [peerigon/markdown-loader#35]
| Property               | Type                                    |  Default  | Comments   |
| -------------          |:-------------:                        | :-----:      | :-----:           |
|prop1?                  | string \| number;                 | 'Def1'      |                     |
|prop2?                  | string &#124; number;       | 'Def2'       |                     |

I have `some.md` file with table and the '|' (pipe) character cant be escaped the way like here (please see the source of this file). It always add new column within the row. It also not works within code marks.

**Comment by meaku** [comment]
This is an issue related to `marked`. Please check their issues and report back if there is something we can do about it.

**Comment by Lazarencjusz** [comment]
@hpohlmeyer thanks, I have updated to latest (v.3) and it works.
