### ISSUE TITLE
npm install marked   也在文档写上哇  以为不需要安装

### ISSUE THREAD

**Issue by xueyida** [peerigon/markdown-loader#36]

**Comment by hpohlmeyer** [comment]
Could you translate that to english?

**Comment by xueyida** [comment]
@hpohlmeyer the module of 'marked' is required, but don't have mentioned  'npm install  marked' in the Instruction.

**Comment by hpohlmeyer** [comment]
Thank you for translating it. The `marked` module is stated as a dependency for `markdown-loader`. It should be installed automatically when installing `markdown-loader`.
