### ISSUE TITLE
Getting newlines "/n" all over rendered markdown

### ISSUE THREAD

**Issue by joepuzzo** [peerigon/markdown-loader#38]
Hey Maybe i'm just doing something wrong but i'm getting newlines all over my rendered markdown. Is there an option to prevent this?

**Comment by hpohlmeyer** [comment]
This is the HTML formatting of [Marked](https://github.com/markedjs/marked). As far as I can see, there is no option to remove line-feeds from the generated HTML.

However, if you use `markdown-loader` with the `html-loader`, you can pass the `minimize` option to `html-loader`, which removes the line-feeds from the generated HTML.

```js
{
  loader: "html-loader",
  options: {
      minimize: true,
  }
}
```
