### ISSUE TITLE
id attribute in heading is not show in the right way when they contains some Chinese

### ISSUE THREAD

**Issue by hangboss1761** [peerigon/markdown-loader#42]
I have a markdown file contains some Chinese like this:

```
# 中文English中文
```

use markdown-loader I got this:

```
<h1 id="-Englist-">中文English中文</h1>
```

I wish I cloud get this:

```
<h1 id="中文Englist中文">中文English中文</h1>
```

id attribute in headings (h1,h2,h3,etc) is not show in the right way

**Comment by meaku** [comment]
@hangboss1761 this is something you have to ask https://www.npmjs.com/package/marked.

**Comment by hangboss1761** [comment]
I see. Thank you!
