### ISSUE TITLE
how to load a markdown file [file.md] without error

### ISSUE THREAD

**Issue by CharlesKumar** [peerigon/markdown-loader#43]
help is wanted 

my config  (nuxt.config.js)

```
  module: {
    rules: [
      {
        test: /\.md$/,
        use: [
          {
            loader: "html-loader"
          },
          {
            loader: "markdown-loader",
            options: {
              pedantic: true,
              renderer
            }
          }
        ]
      }
    ]
  }
```

error occur during nuxt command

 error  in ./assets/markdowns/first.md

```
Module parse failed: Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
| some para
| # Marked
|


 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["G://Experiments//Project//nuxtjs//node_modules//babel-preset-vue-app//dist//index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/marked.vue 8:0-51
 @ ./pages/marked.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
```

What is the necessary step to debug

**Comment by meaku** [comment]
Check out https://github.com/peerigon/markdown-loader/blob/master/example/webpack.config.js. 
You'll also need the HTML loader. And did you define the `renderer` in your code?

**Comment by simonerlandsen** [comment]
I am getting the same thing with the same setup as posted by @CharlesKumar, only without markdown-loader options set. It reports that '#' is an unexpected character and that I need an appropriate loader.

webpack ^4.23.1, markdown-loader ^5.0.0, html-loader ^0.5.5

**Comment by simonerlandsen** [comment]
huh, my problem went away by using the path.resolve on all paths

for example on the entry in the webpack config
``` javascript
// webpack.docs/js

const path = require('path')

module.exports = {

  [...]

  entry: {
    docs: path.resolve(__dirname, '../../docs.js')
  },

  [...]

}

**Comment by kingbrendann** [comment]
I'm having this same problem. Here's my setup: 

File structure:
.
+-- index.js
+-- markdown.md

`webpack.config`:
```
const marked = require('marked');
const markdownRenderer = new marked.Renderer();

const config = {
  module: {
    rules: [
      {
        test: /\.md$/,
        use: [
          {
            loader: 'html-loader'
          },
          {
            loader: 'markdown-loader',
            options: {
              pedantic: true,
              renderer: markdownRenderer
            }
          }
        ]
      }
    ]
  }
}
```

`index.js`:
```
import React, { Component } from 'react';
import source from './markdown.md';

export default class Page extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return (
      <div dangerouslySetInnerHTML={{ __html: source }} />
    );
  }
}
```

`markdown.md`:
```
# Markdown
```

Error on build:
> error uncaughtException: Module parse failed: Unexpected character '#' (3:0)
> You may need an appropriate loader to handle this file type.`
> > # Markdown

**Comment by hpohlmeyer** [comment]
This is most likely a configuration issue. It looks like the `markdown-loader` does not get called.

Webpack assumes the file is a JavaScript file without the loader and fails if it is not valid JS. If you write `console.log('test')` in your markdown file you probably won’t get a compile issue.

If you are sure your loader is running, please provide your whole webpack config or (even better) a reduced test-case.

**Comment by CharlesKumar** [comment]
webpack inline loader just works ! I don't know why inline loader works but config failed however i tried.

try [inline-loader](https://webpack.js.org/concepts/loaders#inline) to load a markdown file.

**Comment by hellolittleBear** [comment]
i think the markdown-loader has some wrong!!!

---

method 1:
```
{
        test: /\.md$/, 
        use: ['markdown-loader', 'html-loader']
},
```
it's wrong:  You may need an appropriate loader to handle this file type...

method 2:
use [inline-loader](https://webpack.js.org/concepts/loaders#inline)
it's  also wrong....

method 3:
delete *markdown-loader* , just  use *html-loader* 、*showdown.js*， it's ok !!!
```
import markFile from '!!html-loader!./article.md'
```

**Comment by ls32140** [comment]
@hellolittleBear hi，my .md file is in asset
![image](https://user-images.githubusercontent.com/26466386/60586900-b60e0100-9dc5-11e9-8876-1963270d69a1.png)
I had install 'markdown-loader', 'html-loader'
angular.json 
![image](https://user-images.githubusercontent.com/26466386/60587135-48160980-9dc6-11e9-9fe3-c79ddf5838b2.png)
I use inline loader like this
`import documentation from '!!html-loader!markdown-loader!./assets/docMd/iOSSdk.md';`
but it not work
![image](https://user-images.githubusercontent.com/26466386/60587309-b6f36280-9dc6-11e9-91b9-63398d34cd00.png)
I don't konw why, if I use wrong document url or config? 
and need typings.d.ts?
![image](https://user-images.githubusercontent.com/26466386/60587447-09348380-9dc7-11e9-8494-f131b53b3bba.png)
My English is not very well,  thang you ~

**Comment by basilvetas** [comment]
> This is most likely a configuration issue. It looks like the `markdown-loader` does not get called.
> 
> Webpack assumes the file is a JavaScript file without the loader and fails if it is not valid JS. If you write `console.log('test')` in your markdown file you probably won’t get a compile issue.
> 
> If you are sure your loader is running, please provide your whole webpack config or (even better) a reduced test-case.


Hey @hpohlmeyer do you have any advice on what to do if this is the issue I'm facing?

I've been trying to debug this issue for a couple days now.  My specific error is: `SyntaxError: Invalid or unexpected token` after trying to load a file `require('../path/to/my/file.md')`  — I tried writing `console.log('test')` in `file.md` as you suggested and I didn't get a compile issue—implying the loader is not running. 

What kind of configuration issues might cause the loader not to run? Any debugging advice or links would be much appreciated.

This is my config for the markdown-loader (I'm also using other loaders defined before it):
```
...
module: {
    rules: [
      ...,
      {
        test: /\.md$/,
        use: [
          {
            loader: 'html-loader'
          },
          {
            loader: 'markdown-loader',
            options: {
              pedantic: true,
              renderer
            }
          }
        ]
      }
    ]
  },
...
```
(I am facing the SyntaxError with and without the extra markdown-loader options)

Thanks!

**Comment by hpohlmeyer** [comment]
@basilvetas That sounds like problem with ES modules. The SSR is done in Node, which only supports CommonJS imports and no ESM syntax. If you use a package that provides an ES module exclusively, you need to transpile it to CommonJS.

In case that this is not the problem, it would be nice if you could provide a test-repo that mirrors your problem.

**Comment by ls32140** [comment]
markdown-loader is not working in my angular item, but raw-loader  is ok.

require(`!!raw-loader!../docMd/file.md`);

**Comment by Rolandisimo** [comment]
As @hellolittleBear mentioned, the full solution for me is:

**1. Define the html-loader and markdown-loader in webpack** both in **server** and **client** part 
```
      rules: [
        // other loaders
        {
          test: /\.md$/,
          use: [
            {
              loader: "html-loader"
            },
            {
              loader: "markdown-loader",
            }
          ]
        },
      ]
```

**2. Import using loaders in path**
`import markFile from '!!html-loader!markdown-loader!./article.md'`

**3. Bonus: Use `markdown-it`**
 to render the md file

**Comment by incomingstick** [comment]
I am also experiencing this issue using Webpack/Typescript/React and can confirm that @hellolittleBear's solution worked for me as well.

It is clear something is not working correctly for the webpack.config.js load, and that you must use the inline loader.

I am not extremely familiar with Webpack, but if there is any additional information I can provide, or anything I can do to help, please let me know

**Comment by joe06102** [comment]
> I am also experiencing this issue using Webpack/Typescript/React and can confirm that @hellolittleBear's solution worked for me as well.
> 
> It is clear something is not working correctly for the webpack.config.js load, and that you must use the inline loader.
> 
> I am not extremely familiar with Webpack, but if there is any additional information I can provide, or anything I can do to help, please let me know

hi, I'm working with typescript & webpack too. And I solved it by specifiy esModule: true in html-loader option. Hope it can solve your problems :D.

```javascript
const mdLoader = {
  test: /\.md$/,
  use: [
    {
      loader: 'html-loader',
      options: {
        esModule: true,
      }
    },
    {
      loader: "markdown-loader",
      options: {
        render: new Marked.Renderer()
      }
    }
  ]
}
```

**Comment by jhnns** [comment]
The original issue was a misconfiguration with the nuxt setup. Closing this one since it's not an issue with the markdown-loader.
