### ISSUE TITLE
License and copyright information

### ISSUE THREAD

**Issue by CidFer** [peerigon/markdown-loader#54]
I was not able to find the copy of the license. Although I was able to see that it is a MIT license, I was not able to find the license itself or the copyright information. Would anybody be able to help?

**Comment by meaku** [comment]
Hello @CidFer! `markdown-loader` is MIT licensed as noted in `README.md` and `package.json`. I added the LICENSE file for you. See https://github.com/peerigon/markdown-loader/blob/master/LICENSE

**Comment by CidFer** [comment]
Hello Michael,

Thank you so much!

I really appreciated.



Em seg, 11 de nov de 2019 às 09:20, Michael Jaser <notifications@github.com>
escreveu:
