### ISSUE TITLE
Changelog for 6.0.0

### ISSUE THREAD

**Issue by Jaid** [peerigon/markdown-loader#64]
Can we please have a rough changelog for 6.0.0? This version got published to npm 2 days ago.

I can't find it in [CHANGELOG.md](https://github.com/peerigon/markdown-loader/blob/e8d693d2021f739fef22cc1a48591db599515f84/CHANGELOG.md) and [GitHub Releases](https://github.com/peerigon/markdown-loader/releases).

**Comment by jhnns** [comment]
Sorry, I forgot to push it. It's online now: https://github.com/peerigon/markdown-loader/blob/master/CHANGELOG.md. I need to automate this soon 😞
